package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"
	"graphql-practice/backend/graph/model"

	"github.com/google/uuid"
)

// SetMessage is the resolver for the setMessage field.
func (r *mutationResolver) SetMessage(ctx context.Context, message string) (*model.Ping, error) {
	return &model.Ping{
		Message: message,
	}, nil
}

// AddTodo is the resolver for the addTodo field.
func (r *mutationResolver) AddTodo(ctx context.Context, title string) (*model.Todo, error) {
	r.mu.Lock()
	defer r.mu.Unlock()

	todo := &model.Todo{
		ID:        uuid.NewString(),
		Title:     title,
		Completed: false,
	}

	r.todos = append(r.todos, todo)
	return todo, nil
}
// ToggleTodo is the resolver for the toggleTodo field.
func (r *mutationResolver) ToggleTodo(ctx context.Context, id string) (*model.Todo, error) {
	r.mu.Lock()
	defer r.mu.Unlock()

	for _, todo := range r.todos {
		if todo.ID == id {
			todo.Completed = !todo.Completed
			return todo, nil
		}
	}

	return nil, fmt.Errorf("todo not found: %s", id)
}
// Ping is the resolver for the ping field.
func (r *queryResolver) Ping(ctx context.Context) (*model.Ping, error) {
	return &model.Ping{
		Message: "pong",
	}, nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	r.mu.Lock()
	defer r.mu.Unlock()

	return r.todos, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
