package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"encoding/json"
	"graphql-practice/backend/graph/model"
)

// SetMessage is the resolver for the setMessage field.
func (r *mutationResolver) SetMessage(ctx context.Context, message string) (*model.Ping, error) {
	return &model.Ping{
		Message: message,
	}, nil
}

// AddTodo is the resolver for the addTodo field.
func (r *mutationResolver) AddTodo(ctx context.Context, title string) (*model.Todo, error) {
	addedTodo, err := r.TodoRepo.Add(ctx, title)
	if err != nil {
		return nil, err
	}

	todo := &model.Todo{
		ID:        addedTodo.ID,
		Title:     addedTodo.Title,
		Completed: addedTodo.Completed,
	}

	event := model.TodoEvent{Type: model.TodoEventTypeAdded, Todo: &model.Todo{
		ID: todo.ID, Title: todo.Title, Completed: todo.Completed,
	}}

	b, _ := json.Marshal(event)
	r.Redis.Publish(ctx, "todo:events", b)

	return event.Todo, nil
}

// ToggleTodo is the resolver for the toggleTodo field.
func (r *mutationResolver) ToggleTodo(ctx context.Context, id string) (*model.Todo, error) {
	todo, _ := r.TodoRepo.Toggle(ctx, id)

	event := model.TodoEvent{Type: model.TodoEventTypeUpdated, Todo: &model.Todo{
		ID: todo.ID, Title: todo.Title, Completed: todo.Completed,
	}}
	b, _ := json.Marshal(event)
	r.Redis.Publish(ctx, "todo:events", b)

	return event.Todo, nil
}

// DeleteTodo is the resolver for the deleteTodo field.
func (r *mutationResolver) DeleteTodo(ctx context.Context, id string) (string, error) {
	r.TodoRepo.Delete(ctx, id)

	event := model.TodoEvent{
		Type: model.TodoEventTypeDeleted,
		Todo: &model.Todo{ID: id},
	}
	b, _ := json.Marshal(event)
	r.Redis.Publish(ctx, "todo:events", b)

	return id, nil
}

// Ping is the resolver for the ping field.
func (r *queryResolver) Ping(ctx context.Context) (*model.Ping, error) {
	return &model.Ping{
		Message: "pong",
	}, nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	todos, _ := r.TodoRepo.List(ctx)
	res := make([]*model.Todo, 0, len(todos))
	for _, t := range todos {
		res = append(res, &model.Todo{
			ID:        t.ID,
			Title:     t.Title,
			Completed: t.Completed,
		})
	}
	return res, nil
}

// TodoEvents is the resolver for the todoEvents field.
func (r *subscriptionResolver) TodoEvents(ctx context.Context) (<-chan *model.TodoEvent, error) {
	ch := make(chan *model.TodoEvent)
	sub := r.Redis.Subscribe(ctx, "todo:events")

	go func() {
		defer close(ch)
		for msg := range sub.Channel() {
			var ev model.TodoEvent
			if err := json.Unmarshal([]byte(msg.Payload), &ev); err == nil {
				ch <- &ev
			}
		}
	}()

	return ch, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
