package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"graphql-practice/backend/graph/model"

)

// SetMessage is the resolver for the setMessage field.
func (r *mutationResolver) SetMessage(ctx context.Context, message string) (*model.Ping, error) {
	return &model.Ping{
		Message: message,
	}, nil
}

func (r *mutationResolver) ToggleTodo(
	ctx context.Context,
	id string,
) (*model.Todo, error) {

	todo, err := r.TodoRepo.Toggle(ctx, id)
	if err != nil {
		return nil, err
	}

	return &model.Todo{
		ID:        todo.ID,
		Title:     todo.Title,
		Completed: todo.Completed,
	}, nil
}

func (r *mutationResolver) AddTodo(
	ctx context.Context,
	title string,
) (*model.Todo, error) {

	todo, err := r.TodoRepo.Add(ctx, title)
	if err != nil {
		return nil, err
	}

	return &model.Todo{
		ID:        todo.ID,
		Title:     todo.Title,
		Completed: todo.Completed,
	}, nil
}
// Ping is the resolver for the ping field.
func (r *queryResolver) Ping(ctx context.Context) (*model.Ping, error) {
	return &model.Ping{
		Message: "pong",
	}, nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(
	ctx context.Context,
) ([]*model.Todo, error) {

	todos, err := r.TodoRepo.List(ctx)
	if err != nil {
		return nil, err
	}

	// graphqlとして返す。
	res := make([]*model.Todo, 0, len(todos))
	for _, t := range todos {
		res = append(res, &model.Todo{
			ID:        t.ID,
			Title:     t.Title,
			Completed: t.Completed,
		})
	}

	return res, nil
}
// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
